import { connectDB } from '../lib/db'
import { Water } from '../models/Water'
import { slugify } from '../lib/utils'

const waters = [
  {
    name: 'Evian Natural Spring Water',
    brand: 'Evian',
    image: 'Core_Range_-_EVIAN-500ML-BOTTLE.png',
    type: 'still' as const,
    country: 'France',
    sourceRegion: 'French Alps',
    ph: 7.2,
    tds: 309,
    hardness: 'hard' as const,
    packaging: 'plastic' as const,
    priceTier: 'premium' as const,
    carbonationLevel: null,
  },
  {
    name: 'Fiji Natural Artesian Water',
    brand: 'Fiji',
    image: 'fiji.webp',
    type: 'still' as const,
    country: 'Fiji',
    sourceRegion: 'Viti Levu Island',
    ph: 7.7,
    tds: 222,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'premium' as const,
    carbonationLevel: null,
  },
  {
    name: 'VOSS Sparkling Water',
    brand: 'VOSS',
    image: 'Voss-Sprk-.37L.webp',
    type: 'sparkling' as const,
    country: 'Norway',
    sourceRegion: 'Iveland',
    ph: 6.0,
    tds: 44,
    hardness: 'soft' as const,
    packaging: 'glass' as const,
    priceTier: 'luxury' as const,
    carbonationLevel: 'medium' as const,
  },
  {
    name: 'Smartwater Vapor Distilled',
    brand: 'Smartwater',
    image: 'smartwater.webp',
    type: 'still' as const,
    country: 'USA',
    sourceRegion: 'Various',
    ph: 7.0,
    tds: 0,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'mid' as const,
    carbonationLevel: null,
  },
  {
    name: 'Saratoga Sparkling Spring Water',
    brand: 'Saratoga',
    image: 'Saratoga-300mL.webp',
    type: 'sparkling' as const,
    country: 'USA',
    sourceRegion: 'Saratoga Springs, NY',
    ph: 6.8,
    tds: 115,
    hardness: 'medium' as const,
    packaging: 'glass' as const,
    priceTier: 'premium' as const,
    carbonationLevel: 'light' as const,
  },
  {
    name: 'Liquid Death Mountain Water',
    brand: 'Liquid Death',
    image: 'liquid death.webp',
    type: 'still' as const,
    country: 'USA',
    sourceRegion: 'Austrian Alps',
    ph: 8.0,
    tds: 120,
    hardness: 'medium' as const,
    packaging: 'aluminum' as const,
    priceTier: 'mid' as const,
    carbonationLevel: null,
  },
  {
    name: 'Box Water',
    brand: 'Box Water Is Better',
    image: 'box water.avif',
    type: 'still' as const,
    country: 'USA',
    sourceRegion: 'Municipal',
    ph: 7.4,
    tds: 50,
    hardness: 'soft' as const,
    packaging: 'carton' as const,
    priceTier: 'mid' as const,
    carbonationLevel: null,
  },
  {
    name: 'Poland Spring Origin',
    brand: 'Poland Spring',
    image: 'Poland-Spring-600.webp',
    type: 'still' as const,
    country: 'USA',
    sourceRegion: 'Maine',
    ph: 6.8,
    tds: 37,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'budget' as const,
    carbonationLevel: null,
  },
  {
    name: 'Core Hydration Perfectly Balanced Water',
    brand: 'Core Hydration',
    image: 'core-hydration-water-16-9oz-bottle-rpet.webp',
    type: 'alkaline' as const,
    country: 'USA',
    sourceRegion: 'Various',
    ph: 7.4,
    tds: 70,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'mid' as const,
    carbonationLevel: null,
  },
  {
    name: 'Dasani Purified Water',
    brand: 'Dasani',
    image: 'dasani-blp-product.webp',
    type: 'still' as const,
    country: 'USA',
    sourceRegion: 'Municipal',
    ph: 7.0,
    tds: 30,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'budget' as const,
    carbonationLevel: null,
  },
  {
    name: 'Icelandic Glacial Natural Spring Water',
    brand: 'Icelandic Glacial',
    image: 'icelandic water.webp',
    type: 'still' as const,
    country: 'Iceland',
    sourceRegion: 'Ölfus Spring',
    ph: 8.4,
    tds: 62,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'premium' as const,
    carbonationLevel: null,
  },
  {
    name: 'Kirkland Signature Alkaline Water',
    brand: 'Kirkland Signature',
    image: 'kirkland alkaline.webp',
    type: 'alkaline' as const,
    country: 'USA',
    sourceRegion: 'Various',
    ph: 9.5,
    tds: 20,
    hardness: 'soft' as const,
    packaging: 'plastic' as const,
    priceTier: 'budget' as const,
    carbonationLevel: null,
  },
]

async function seed() {
  await connectDB()
  await Water.deleteMany({})
  const docs = waters.map(w => ({ ...w, slug: slugify(w.brand + ' ' + w.name) }))
  await Water.insertMany(docs)
  console.log(`Seeded ${docs.length} waters`)
  process.exit(0)
}

seed().catch(err => { console.error(err); process.exit(1) })
